### ISSUE TITLE
中文博客圈邀请函

### ISSUE THREAD

**Issue by huhexian** [guyskk/guyskk.github.io#3]
博主，邀请你加入中文博客圈QQ群193263179

**Comment by guyskk** [comment]
感谢邀请，我的文章可随意转发，前提是注明作者和原文链接。

**Comment by huhexian** [comment]
哈，不用，不会转载文章的

**Comment by guyskk** [comment]
@hhx546642451 非常感谢你把蚁阅推荐给BlogHub的朋友！之前我误会成广告群了，请多包涵~
